version: 0.4{build}
image: Visual Studio 2019

build_script:
  - ps: .\build.ps1 -Target "Appveyor" -Configuration Release

# disable built-in tests.
test: off

artifacts:
- path: output\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: kOU0XIA3C3CzXhKPk28ty1DIkOeJNpshuk2yWQDq/rHVeFCf3Y/neNOho9epDa7e
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/