version: 0.7.{build}
image: Visual Studio 2019
  
skip_non_tags: false

build_script:
  - ps: .\build.ps1 -Target "Appveyor" -Configuration Release

# disable built-in tests.
test: off

artifacts:
- path: output\*.nupkg